# Generated by Django 5.2.7 on 2025-11-07 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en cours', 'en cours'), ('validée', 'Validée'), ('payee', 'Payée'), ('livraison', 'En livraison'), ('terminée', 'terminée'), ('Zombie', 'Zombie')], default='en cours', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='panier',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'actif')), fields=('client', 'status'), name='un_seul_panier_actif_par_client'),
        ),
    ]
