# Generated by Django 5.2.7 on 2025-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_commande_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('Chargement', 'Chargement'), ('validée', 'Validée'), ('payee', 'Payée'), ('livraison', 'En livraison'), ('terminée', 'terminée'), ('Zombie', 'Zombie'), ('Reactivé', 'Reactivé')], default='Chargement', max_length=20),
        ),
    ]
