# Generated by Django 5.2.7 on 2025-11-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_alter_commande_statut'),
        ('payement_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='stripe_payement_intent_id',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='order_app.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('carte_ligdicash', 'Carte Bancaire(ligdicash)'), ('mobile_ligdicash', 'Mobile Money (Ligdicash)')], max_length=20),
        ),
    ]
