# Generated by Django 5.2.7 on 2025-11-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_categories_products_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='products_images/'),
        ),
    ]
