# Generated by Django 5.2.7 on 2025-11-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_search_by_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
                ('nb_resultats', models.IntegerField(default=0)),
            ],
        ),
    ]
