# Generated by Django 5.2.7 on 2025-11-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='services_app.categories'),
        ),
    ]
