# Generated by Django 5.2.7 on 2025-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_categories_icone_categories_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='comment',
            new_name='commentaire',
        ),
        migrations.AddField(
            model_name='realisation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
